name: 'metrics_framework_playbook'
version: '1.0.0'
config-version: 2
required-dbt-version: ''>=0.18.0'

profile: 'playbook'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:        
    - "target"
    - "dbt_modules"
    
seeds:
  quote_columns: false

models:
  metrics_framework_playbook:
    marts:
      +materialized: table
    staging:
      +materialized: view

on-run-end:
  "{{ grant_select_on_schemas(schemas, 'reporter') }}"
